dataset_dir: /home/dzubke/awni_speech/data/speak_test_data/eval/eval2/v4/random/ # directory where the dataset is located
dataset_files:           # dataset filenames to be processed, files should be in dataset_dir
    train: eval2-v4_data_2020-12-09.tsv
dataset_name: SpeakTrain # Name of dataset with a capitalized first letter
lexicon_path: /home/dzubke/awni_speech/speech-lfs/examples/common-voice/cv-lex-extended_2020-07-16.txt #path to pronunciation lexicon
force_convert: False    # Converts audio to wav file even if .wav file already exists
min_duration: 1         # minimum audio duration in seconds
max_duration: 20        # maximum audio duration in seconds
