
eval_type: 'eval2'
models:
    model_spk-100:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201124/ph5/
        tag: best
        filename: model_state_dict.pth
    model_spk-250:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201124/ph6/
        tag: best
        filename: model_state_dict.pth
    model_spk-500:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201124/ph7/
        tag: best
        filename: model_state_dict.pth
    model_spk-1000:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20200925/ph3/
        tag: best
        filename: model_state_dict.pth
    model_1118:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201029/ph7/20201118/
        tag: best
        filename: model_state_dict.pth
    model_0806:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20200806/ph4/
        tag: best
        filename: model_state_dict.pth
    model_0902:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20200826/ph2/20200902/
        tag: 
        filename: model_state_dict.pth
    model_0406:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20200406/20200409/
        tag: best
        filename: model
datasets: 
    speak-eval2-v3: /home/dzubke/awni_speech/data/speak_test_data/eval/eval2/speak-eval2-v3_2020-12-08.json
output_path: /home/dzubke/awni_speech/speech-lfs/evaluate/output/eval2-v3_7-model_2020-12-08.txt
lexicon_path: /home/dzubke/awni_speech/speech-lfs/examples/master-lexicon_2020-08-05.txt
