eval_type: 'eval2'
models:
    #model_spk-100:
    #    path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201124/ph5/
    #    tag: best
    #    filename: model_state_dict.pth
    #model_spk-250:
    #    path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201124/ph6/
    #    tag: best
    #    filename: model_state_dict.pth
    #model_spk-500:
    #    path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201124/ph7/
    #    tag: best
    #    filename: model_state_dict.pth
    model_spk-1000:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20200925/ph3/
        tag: best
        filename: model_state_dict.pth
   # model_1118:
   #     path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20201029/ph7/20201118/
   #     tag: best
   #     filename: model_state_dict.pth
   # model_0902:
   #     path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20200826/ph2/20200902/
   #     tag: 
   #     filename: model_state_dict.pth
   # model_0406:
   #     path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20200406/20200409/
   #     tag: best
   #     filename: model
datasets: 
    speak-eval2-v7: /home/dzubke/awni_speech/data/speak_test_data/eval/eval2/speak-eval2-v7_2020-12-16.json
    speak-eval2-v6: /home/dzubke/awni_speech/data/speak_test_data/eval/eval2/speak-eval2-v6_2020-12-16.json
    speak-eval2-v2: /home/dzubke/awni_speech/data/speak_test_data/eval/eval2-v2_1000/speak-eval2-v2_2020-12-07.json
output_path: /home/dzubke/awni_speech/speech-lfs/evaluate/output/eval2-test.txt
lexicon_path: /home/dzubke/awni_speech/speech-lfs/examples/master-lexicon_2020-08-05.txt
