eval_type: 'eval1' 
models:
    model_swb:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20210126/ph4/
        tag: best
        filename: model_state_dict.pth
    model_spk-250:
        path: /home/dzubke/awni_speech/speech-lfs/examples/librispeech/models/ctc_models/20210106/ph5/
        tag: best
        filename: model_state_dict.pth
dataset_path: /mnt/disks/data_disk/data/speak_test_data/eval/eval1_400/eval1_data_2020-11-20.tsv
output_path: /home/dzubke/awni_speech/speech-lfs/evaluate/eval1_swb_2021-01-29.txt
lexicon_path: /home/dzubke/awni_speech/speech-lfs/data/lexicon/master-lexicon_2020-08-05.txt
n_top_beams: 1
